description: "Build .NET app"

parameters:
  app_directory:
    description: Select a specific version of the .NET Core framework.
    default: "deployapp"
    type: string
steps:
  - run:
      name: Build .NET app - <<parameters.app_directory>>
      environment:
        PARAM_DOTNET_APP_DIRECTORY: <<parameters.app_directory>>
      command: <<include(scripts/build_dotnet_app.sh)>>
