description: >
  Sample description install job
# What will this job do?
# Descriptions should be short, simple, and clear.

executor: default

parameters:
  app_directory:
    description: Select a specific version of the .NET Core framework.
    default: "deployapp"
    type: string
steps:
  - build:
      app_directory: << parameters.app_directory >>
